CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150),
  "email" varchar(150) UNIQUE,
  "password" varchar(50),
  "avatar" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "friend_request_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50)
);

CREATE TABLE "friends" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "requester_id" int,
  "receiver_id" int,
  "status_id" int,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "chats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(20),
  "name" varchar(100),
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "chat_members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" int,
  "user_id" int,
  "joined_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" int,
  "sender_id" int,
  "content" text,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

ALTER TABLE "friends" ADD FOREIGN KEY ("requester_id") REFERENCES "users" ("id");
ALTER TABLE "friends" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");
ALTER TABLE "friends" ADD FOREIGN KEY ("status_id") REFERENCES "friend_request_status" ("id");
ALTER TABLE "chat_members" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");
ALTER TABLE "chat_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "messages" ADD FOREIGN KEY ("chat_id") REFERENCES "chats" ("id");
ALTER TABLE "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");